# This script holds parameters specific to an instance of a build 
#fake pr
export CB_BRANCH=master
export CB_CHECK_GREEN_SHA_AGE=true
export CB_COMMIT=
export CB_DOCKER_HUB=gcr.io/istio-release
export CB_GCS_BUILD_BUCKET=istio-release-pipeline-data
export CB_GCS_BUILD_PATH=istio-release-pipeline-data/daily-build/krishna-test2
export CB_GCS_FULL_STAGING_PATH=istio-prerelease/daily-build/krishna-test2
export CB_GCS_MONTHLY_RELEASE_PATH=
export CB_GCS_RELEASE_TOOLS_PATH=istio-release-pipeline-data/release-tools/daily-build/krishna-test2
export CB_GCS_STAGING_BUCKET=istio-prerelease
export CB_GITHUB_ORG=krishna
export CB_GITHUB_TOKEN_FILE_PATH=istio-secrets/github.txt.enc
export CB_ISTIOCTL_DOCKER_HUB=gcr.io/istio-release
export CB_PIPELINE_TYPE=daily
export CB_PUSH_DOCKER_HUBS=gcr.io/istio-release
export CB_TEST_GITHUB_TOKEN_FILE_PATH=
export CB_VERIFY_CONSISTENCY=false
export CB_VERSION=krishna-test2
